=== ArudenKun/scoop-bucket/scoop-schema.json
{
    "$id": "http://scoop.sh/draft/schema#",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "definitions": {
      "hashPattern": {
        "pattern": "^([a-fA-F0-9]{64}|(sha1|sha256|sha512|md5):([a-fA-F0-9]{32}|[a-fA-F0-9]{40}|[a-fA-F0-9]{64}|[a-fA-F0-9]{128}))$",
        "type": "string"
      },
      "jsonPathPattern": {
        "pattern": "^\\$[.\\[].*$",
        "type": "string"
      },
      "hash": {
        "anyOf": [
          {
            "$ref": "#/definitions/hashPattern"
          },
          {
            "items": {
              "$ref": "#/definitions/hashPattern"
            },
            "minItems": 1,
            "type": "array",
            "uniqueItems": true
          }
        ]
      },
      "hashExtraction": {
        "additionalProperties": false,
        "properties": {
          "find": {
            "format": "regex",
            "type": "string",
            "description": "Same as 'regex'"
          },
          "regex": {
            "format": "regex",
            "type": "string"
          },
          "jp": {
            "$ref": "#/definitions/jsonPathPattern",
            "description": "Same as 'jsonpath'"
          },
          "jsonpath": {
            "$ref": "#/definitions/jsonPathPattern"
          },
          "xpath": {
            "type": "string"
          },
          "mode": {
            "enum": [
              "download",
              "extract",
              "json",
              "xpath",
              "rdf",
              "metalink",
              "fosshub",
              "sourceforge",
              "github"
            ]
          },
          "type": {
            "enum": [
              "md5",
              "sha1",
              "sha256",
              "sha512"
            ],
            "description": "Deprecated, hash type is determined automatically"
          },
          "url": {
            "anyOf": [
              {
                "format": "uri",
                "type": "string"
              },
              {
                "pattern": "^(\\$url|\\$baseurl).[\\w\\d]+$",
                "type": "string"
              },
              {
                "pattern": "^.*(\\$url|\\$baseurl).*$",
                "type": "string"
              }
            ]
          }
        },
        "type": "object"
      },
      "hashExtractionOrArrayOfHashExtractions": {
        "anyOf": [
          {
            "$ref": "#/definitions/hashExtraction"
          },
          {
            "items": {
              "$ref": "#/definitions/hashExtraction"
            },
            "minItems": 1,
            "type": "array",
            "uniqueItems": false
          }
        ]
      },
      "architecture": {
        "additionalProperties": false,
        "properties": {
          "bin": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
          },
          "checkver": {
            "$ref": "#/definitions/checkver"
          },
          "env_add_path": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "env_set": {
            "type": "object"
          },
          "extract_dir": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "hash": {
            "$ref": "#/definitions/hash"
          },
          "installer": {
            "$ref": "#/definitions/installer"
          },
          "msi": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Deprecated"
          },
          "post_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "post_uninstall": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "pre_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "pre_uninstall": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "shortcuts": {
            "$ref": "#/definitions/shortcutsArray"
          },
          "uninstaller": {
            "$ref": "#/definitions/uninstaller"
          },
          "url": {
            "$ref": "#/definitions/uriOrArrayOfUris"
          }
        },
        "type": "object"
      },
      "arrayOfArrayOfStrings": {
        "items": {
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "type": "array"
        },
        "minItems": 1,
        "type": "array"
      },
      "shortcutsArray": {
        "items": {
          "items": {
            "type": "string"
          },
          "minItems": 2,
          "maxItems": 4,
          "type": "array"
        },
        "minItems": 1,
        "type": "array"
      },
      "autoupdateArch": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "bin": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
          },
          "env_add_path": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "env_set": {
            "type": "object"
          },
          "extract_dir": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "hash": {
            "$ref": "#/definitions/hashExtractionOrArrayOfHashExtractions"
          },
          "installer": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "file": {
                "type": "string"
              }
            }
          },
          "shortcuts": {
            "$ref": "#/definitions/shortcutsArray"
          },
          "url": {
            "$ref": "#/definitions/autoupdateUriOrArrayOfAutoupdateUris"
          }
        }
      },
      "autoupdate": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "architecture": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "32bit": {
                "$ref": "#/definitions/autoupdateArch"
              },
              "64bit": {
                "$ref": "#/definitions/autoupdateArch"
              },
              "arm64": {
                "$ref": "#/definitions/autoupdateArch"
              }
            }
          },
          "bin": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
          },
          "env_add_path": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "env_set": {
            "type": "object"
          },
          "extract_dir": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "hash": {
            "$ref": "#/definitions/hashExtractionOrArrayOfHashExtractions"
          },
          "installer": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "file": {
                "type": "string"
              }
            }
          },
          "license": {
            "$ref": "#/definitions/license"
          },
          "notes": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "persist": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
          },
          "psmodule": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "name": {
                "type": "string"
              }
            }
          },
          "shortcuts": {
            "$ref": "#/definitions/shortcutsArray"
          },
          "url": {
            "$ref": "#/definitions/autoupdateUriOrArrayOfAutoupdateUris"
          }
        }
      },
      "checkver": {
        "anyOf": [
          {
            "format": "regex",
            "type": "string"
          },
          {
            "additionalProperties": false,
            "properties": {
              "github": {
                "format": "uri",
                "type": "string"
              },
              "re": {
                "format": "regex",
                "type": "string",
                "description": "Same as 'regex'"
              },
              "regex": {
                "format": "regex",
                "type": "string"
              },
              "url": {
                "format": "uri",
                "type": "string"
              },
              "jp": {
                "$ref": "#/definitions/jsonPathPattern",
                "description": "Same as 'jsonpath'"
              },
              "jsonpath": {
                "$ref": "#/definitions/jsonPathPattern"
              },
              "xpath": {
                "type": "string"
              },
              "reverse": {
                "description": "Reverse the order of regex matches",
                "type": "boolean"
              },
              "replace": {
                "description": "Allows rearrange the regexp matches",
                "type": "string"
              },
              "useragent": {
                "type": "string"
              },
              "script": {
                "$ref": "#/definitions/stringOrArrayOfStrings",
                "description": "Custom PowerShell script to retrieve application version using more complex approach."
              },
              "sourceforge": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "additionalProperties": false,
                    "properties": {
                      "project": {
                        "type": "string"
                      },
                      "path": {
                        "type": "string"
                      }
                    },
                    "type": "object"
                  }
                ]
              }
            },
            "type": "object"
          }
        ]
      },
      "installer": {
        "additionalProperties": false,
        "properties": {
          "_comment": {
            "description": "Undocumented: only used in scoop-extras/oraclejdk* and scoop-extras/appengine-go",
            "type": "string"
          },
          "args": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "file": {
            "type": "string"
          },
          "script": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "keep": {
            "type": "boolean"
          }
        },
        "type": "object"
      },
      "stringOrArrayOfStrings": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "items": {
              "type": "string"
            },
            "minItems": 1,
            "type": "array"
          }
        ]
      },
      "stringOrArrayOfStringsOrAnArrayOfArrayOfStrings": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "items": {
              "$ref": "#/definitions/stringOrArrayOfStrings"
            },
            "minItems": 1,
            "type": "array"
          }
        ]
      },
      "uninstaller": {
        "properties": {
          "args": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "file": {
            "type": "string"
          },
          "script": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          }
        },
        "oneOf": [
          {
            "required": [
              "file"
            ]
          },
          {
            "required": [
              "script"
            ]
          }
        ],
        "type": "object"
      },
      "uriOrArrayOfUris": {
        "anyOf": [
          {
            "format": "uri",
            "not": {
              "pattern": "(\\$)"
            },
            "type": "string"
          },
          {
            "items": {
              "format": "uri",
              "not": {
                "pattern": "(\\$)"
              },
              "type": "string"
            },
            "minItems": 1,
            "type": "array",
            "uniqueItems": true
          }
        ]
      },
      "autoupdateUriOrArrayOfAutoupdateUris": {
        "anyOf": [
          {
            "format": "uri",
            "type": "string"
          },
          {
            "items": {
              "format": "uri",
              "type": "string"
            },
            "minItems": 1,
            "type": "array",
            "uniqueItems": true
          }
        ]
      },
      "licenseIdentifiers": {
        "type": "string",
        "description": "License identifier based on SPDX License List https://spdx.org/licenses/",
        "examples": [
          "Apache-2.0",
          "BSD-3-Clause",
          "Freeware",
          "GPL-2.0-only",
          "GPL-2.0-or-later",
          "GPL-3.0-only",
          "GPL-3.0-or-later",
          "ISC",
          "LGPL-2.0-only",
          "LGPL-2.0-or-later",
          "LGPL-2.1-only",
          "LGPL-2.1-or-later",
          "LGPL-3.0-only",
          "LGPL-3.0-or-later",
          "MIT",
          "MS-PL",
          "Proprietary",
          "Public Domain",
          "Shareware",
          "Unlicense"
        ]
      },
      "license": {
        "anyOf": [
          {
            "$ref": "#/definitions/licenseIdentifiers"
          },
          {
            "additionalProperties": false,
            "properties": {
              "url": {
                "format": "uri",
                "type": "string"
              },
              "identifier": {
                "$ref": "#/definitions/licenseIdentifiers"
              }
            },
            "required": [
              "identifier"
            ],
            "type": "object"
          }
        ]
      }
    },
    "properties": {
      "$schema": {
        "type": "string",
        "format": "uri"
      },
      "_comment": {
        "description": "Deprecated. Use ## instead.",
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "##": {
        "description": "A comment.",
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "architecture": {
        "additionalProperties": false,
        "properties": {
          "32bit": {
            "$ref": "#/definitions/architecture"
          },
          "64bit": {
            "$ref": "#/definitions/architecture"
          },
          "arm64": {
            "$ref": "#/definitions/architecture"
          }
        },
        "type": "object"
      },
      "autoupdate": {
        "$ref": "#/definitions/autoupdate"
      },
      "bin": {
        "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
      },
      "persist": {
        "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
      },
      "checkver": {
        "$ref": "#/definitions/checkver"
      },
      "cookie": {
        "description": "Undocumented: Found at https://github.com/se35710/scoop-java/search?l=JSON&q=cookie",
        "type": "object"
      },
      "depends": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "description": {
        "type": "string"
      },
      "env_add_path": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "env_set": {
        "type": "object"
      },
      "extract_dir": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "extract_to": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "hash": {
        "$ref": "#/definitions/hash"
      },
      "homepage": {
        "format": "uri",
        "type": "string"
      },
      "innosetup": {
        "description": "True if the installer InnoSetup based. Found in https://github.com/ScoopInstaller/Main/search?l=JSON&q=innosetup",
        "type": "boolean"
      },
      "installer": {
        "$ref": "#/definitions/installer"
      },
      "license": {
        "$ref": "#/definitions/license"
      },
      "msi": {
        "$ref": "#/definitions/stringOrArrayOfStrings",
        "description": "Deprecated"
      },
      "notes": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "post_install": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "post_uninstall": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "pre_install": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "pre_uninstall": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "psmodule": {
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "shortcuts": {
        "$ref": "#/definitions/shortcutsArray"
      },
      "suggest": {
        "additionalProperties": false,
        "patternProperties": {
          "^(.*)$": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          }
        },
        "type": "object"
      },
      "uninstaller": {
        "$ref": "#/definitions/uninstaller"
      },
      "url": {
        "$ref": "#/definitions/uriOrArrayOfUris"
      },
      "version": {
        "pattern": "^[\\w\\.\\-+_]+$",
        "type": "string"
      }
    },
    "if": {
      "properties": {
        "architecture": {
          "properties": {
            "64bit": {
              "properties": {
                "url": false
              }
            },
            "32bit": {
              "properties": {
                "url": false
              }
            },
            "arm64": {
              "properties": {
                "url": false
              }
            }
          }
        }
      }
    },
    "then": {
      "required": [
        "url"
      ]
    },
    "required": [
      "version",
      "homepage",
      "license"
    ],
    "title": "scoop app manifest schema",
    "type": "object"
  }

=== ArudenKun/scoop-bucket/bucket/vcredist-aio.json
{
    "version": "0.69.0",
    "description": "All-in-one repack for latest Microsoft Visual C++ Redistributable Runtimes, without the original setup bloat payload.",
    "homepage": "https://github.com/abbodi1406/vcredist",
    "license": "Unlicense",
    "url": "https://github.com/abbodi1406/vcredist/releases/download/v0.69.0/VisualCppRedist_AIO_x86_x64_69.zip",
    "hash": "535c08bf72ae8a982d965b6931944f9c5686ac1f8ac8b3d34833d55454a235c2",
    "installer": {
        "script": [
            "if (!(is_admin)) { error 'This package requires admin rights to install'; break }",
            "Start-Process -Wait \"$dir\\VisualCppRedist_AIO_x86_x64.exe\" -ArgumentList @('/aiM', '/gm2') -Verb RunAs"
        ]
    },
    "bin": "VisualCppRedist_AIO_x86_x64.exe",
    "uninstaller": {
        "script": [
            "if (!(is_admin)) { error 'This package requires admin rights to uninstall'; break }",
            "Start-Process -Wait \"$dir\\VisualCppRedist_AIO_x86_x64.exe\" -ArgumentList @('/aiM', '/gm2') -Verb RunAs"
        ]
    },
    "checkver": {
        "github": "https://github.com/abbodi1406/vcredist"
    },
    "autoupdate": {
        "url": "https://github.com/abbodi1406/vcredist/releases/download/v$version/VisualCppRedist_AIO_x86_x64_$minorVersion.zip",
        "hash": {
            "url": "https://github.com/abbodi1406/vcredist/releases/v$version",
            "regex": "File: $basename[\\S\\s]*?SHA-256: $sha256"
        }
    }
}

=== ArudenKun/scoop-bucket/bucket/mremoteng-portapps.json
{
    "version": "1.76.20-9",
    "description": "An open source, tabbed, multi-protocol, remote connections manager.",
    "homepage": "https://mremoteng.org/",
    "license": {
        "identifier": "GPL-2.0-only",
        "url": "https://github.com/mRemoteNG/mRemoteNG/blob/develop/COPYING.TXT"
    },
    "url": "https://github.com/portapps/mremoteng-portable/releases/download/1.76.20-9/mremoteng-portable-win32-1.76.20-9.7z#/dl.7z",
    "hash": "cf348b533e45995b2c339feb47303681896a3816d449e1104ada0e8c8b28a111",
    "persist": [
        "data",
        "mremoteng-portable.yml"
    ],
    "shortcuts": [
        [
            "mremoteng-portable.exe",
            "mRemoteNG"
        ]
    ],
    "pre_install": "if(!(Test-Path \"$persist_dir\\mremoteng-portable.yml\")) { New-Item \"$dir\\mremoteng-portable.yml\" | Out-Null }",
    "checkver": {
        "url": "https://github.com/portapps/mremoteng-portable/releases",
        "regex": "\\/releases\\/tag\\/(?:v|V)?([\\d.-]+)"
    },
    "autoupdate": {
        "url": "https://github.com/portapps/mremoteng-portable/releases/download/$version/mremoteng-portable-win32-$version.7z#/dl.7z",
        "hash": {
            "url": "$baseurl/checksums.txt"
        }
    },
    "notes": "Installed from Portapps (https://portapps.io/app/mremoteng-portable/)"
}

=== ArudenKun/scoop-bucket/deprecated/collapse.json
{
    "version": "nightly",
    "homepage": "https://github.com/neon-nyan/Collapse",
    "license": "MIT",
    "url": "https://raw.githubusercontent.com/CollapseLauncher/Collapse/main/CollapseLauncher/icon.ico",
    "installer": {
        "script": [
            "try {",
            "   $url = 'https://api.github.com/repos/CollapseLauncher/Collapse/releases/latest'",
            "   $release_cont = $(Invoke-WebRequest $url).Content | ConvertFrom-Json",
            "   $link = $release_cont.assets[1].browser_download_url",
            "   $asset_name = $release_cont.assets[1].name",
            "   aria2c $link -d $dir",
            "   Expand-7zipArchive \"$dir\\$asset_name\" -Removal",
            "}",
            "catch { error $_.Exception.Message; throw }"
        ]
    },
    "shortcuts": [
        [
            "CollapseLauncher.exe",
            "Collapse"
        ]
    ],
    "post_install": "Remove-Item $dir\\icon.ico",
    "##": [
        "url: https://github.com/neon-nyan/Collapse/releases/download/CL-v1.70.14/CL-1.70.14_Portable.7z",
        "url: https://github.com/neon-nyan/Collapse/releases/download/CL-v$version/CL-$version_Portable.7z",
        "url: https://github.com/neon-nyan/Collapse/tags",
        "regex: /archive/refs/tags/CL-v([\\d.]+).zip"
    ]
}

=== ArudenKun/scoop-bucket/bucket/msedge.json
{
    "homepage": "https://www.microsoft.com/en-us/edge",
    "description": "The chromium based Microsoft Edge browser",
    "version": "115.0.1901.203",
    "license": "Freeware",
    "architecture": {
        "64bit": {
            "url": "https://dorado-api.deno.dev/edge?arch=64&channel=stable&version=115.0.1901.203&dl#/MicrosoftEdge-115.0.1901.203-x64.7z",
            "hash": "52695a998c0aabd5ef2e39b05ec27073a44a3e0efc65eed1bd252f92e9f2c0e1"
        },
        "32bit": {
            "url": "https://dorado-api.deno.dev/edge?arch=86&channel=stable&version=115.0.1901.203&dl#/MicrosoftEdge-115.0.1901.203-x86.7z",
            "hash": "a9a0a69336c7d7e8e591d58567d32859dedbd9172042a9d574c580d0188e9283"
        },
        "arm64": {
            "url": "https://dorado-api.deno.dev/edge?arch=arm64&channel=stable&version=115.0.1901.203&dl#/MicrosoftEdge-115.0.1901.203-arm64.7z",
            "hash": "c948e6ff08e34e9ff70c77b97e9d3527d85823f025d638af02cf3cd3920f6a46"
        }
    },
    "installer": {
        "script": "Expand-7zipArchive -Path \"$dir\\MSEDGE.7z\" -ExtractDir \"Chrome-bin\\$version\" -Removal"
    },
    "shortcuts": [
        [
            "msedge.exe",
            "Microsoft Edge"
        ]
    ],
    "checkver": {
        "url": "https://dorado-api.deno.dev/edge?arch=64&channel=stable",
        "jsonpath": "$.Version"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://dorado-api.deno.dev/edge?arch=64&channel=stable&version=$version&dl#/MicrosoftEdge-$version-x64.7z",
                "hash": {
                    "url": "https://dorado-api.deno.dev/edge?arch=64&channel=stable&version=$version",
                    "jsonpath": "$.Hashes.Sha256"
                }
            },
            "32bit": {
                "url": "https://dorado-api.deno.dev/edge?arch=86&channel=stable&version=$version&dl#/MicrosoftEdge-$version-x86.7z",
                "hash": {
                    "url": "https://dorado-api.deno.dev/edge?arch=86&channel=stable&version=$version",
                    "jsonpath": "$.Hashes.Sha256"
                }
            },
            "arm64": {
                "url": "https://dorado-api.deno.dev/edge?arch=arm64&channel=stable&version=$version&dl#/MicrosoftEdge-$version-arm64.7z",
                "hash": {
                    "url": "https://dorado-api.deno.dev/edge?arch=arm64&channel=stable&version=$version",
                    "jsonpath": "$.Hashes.Sha256"
                }
            }
        }
    }
}

=== ArudenKun/scoop-bucket/bucket/handbrake-portapps.json
{
    "version": "1.5.1-8",
    "description": "A tool for converting video from nearly any format to a selection of modern, widely supported codecs.",
    "homepage": "https://handbrake.fr/",
    "license": "https://github.com/HandBrake/HandBrake/blob/master/LICENSE",
    "persist": [
        "data",
        "handbrake-portable.yml"
    ],
    "architecture": {
        "64bit": {
            "url": "https://github.com/portapps/handbrake-portable/releases/download/1.5.1-8/handbrake-portable-win64-1.5.1-8.7z#/dl.7z",
            "hash": "5bb4934a723bfd37a69e4d70e994adc7a129bc593fa1ea750bd721df5401dcb5"
        }
    },
    "shortcuts": [
        [
            "handbrake-portable.exe",
            "Handbrake"
        ]
    ],
    "pre_install": "if(!(Test-Path \"$persist_dir\\handbrake-portable.yml\")) { New-Item \"$dir\\handbrake-portable.yml\" | Out-Null }",
    "checkver": {
        "url": "https://github.com/portapps/handbrake-portable/releases",
        "regex": "\\/releases\\/tag\\/(?:v|V)?([\\d.-]+)"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/portapps/handbrake-portable/releases/download/$version/handbrake-portable-win64-$version.7z#/dl.7z"
            }
        },
        "hash": {
            "url": "$baseurl/checksums.txt"
        }
    },
    "notes": "Installed from Portapps (https://portapps.io/app/handbrake-portable/)"
}

=== ArudenKun/scoop-bucket/bucket/mpv.net-beta.json
{
    "version": "6.0.3.2",
    "description": "A modern media player for Windows that works just like mpv",
    "homepage": "https://github.com/mpvnet-player/mpv.net/",
    "license": "GPL-2.0-or-later",
    "architecture": {
        "64bit": {
            "url": "https://github.com/mpvnet-player/mpv.net/releases/download/v6.0.3.2-beta/mpv.net-6.0.3.2-beta.zip",
            "hash": "81975f82de761320e06f11f59a6983348c64d110f89a8a1779ba8a4a80813176"
        }
    },
    "bin": [
        "mpvnet.com",
        [
            "mpvnet.com",
            "mpv"
        ]
    ],
    "shortcuts": [
        [
            "mpvnet.exe",
            "mpv.net"
        ]
    ],
    "persist": "portable_config",
    "checkver": {
        "url": "https://api.github.com/repositories/101537172/releases",
        "jsonpath": "$.[0].assets[0].name",
        "regex": "mpv.net-(?<stable>v)?([\\d.-]+)(?<beta>-beta)?.zip"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/mpvnet-player/mpv.net/releases/download/v$version$matchBeta/mpv.net-$matchStable$version$matchBeta.zip"
            }
        }
    }
}

=== ArudenKun/scoop-bucket/bucket/autoruns.json
{
    "version": "14.09",
    "homepage": "https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns",
    "description": "See what programs are configured to startup automatically when your system boots and you login.",
    "license": {
        "identifier": "Microsoft SysInternals EULA",
        "url": "https://docs.microsoft.com/en-us/sysinternals/license-terms"
    },
    "url": "https://download.sysinternals.com/files/Autoruns.zip",
    "hash": "f82294355e98051aed850e567c676466c16beca333e1fe96fe7cab003e987764",
    "architecture": {
        "64bit": {
            "shortcuts": [
                [
                    "Autoruns64.exe",
                    "Autoruns"
                ]
            ]
        },
        "32bit": {
            "shortcuts": [
                [
                    "Autoruns.exe",
                    "Autoruns"
                ]
            ]
        }
    },
    "checkver": {
        "re": "Autoruns for Windows v([\\d.]+)"
    },
    "autoupdate": {
        "url": "https://download.sysinternals.com/files/Autoruns.zip",
        "hash": {
            "url": "https://plunger-dotnet-api.herokuapp.com/autoruns",
            "jp": "$.sha256"
        }
    }
}
