=== ArudenKun/scoop-bucket/scoop-schema.json
{
    "$id": "http://scoop.sh/draft/schema#",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "definitions": {
      "hashPattern": {
        "pattern": "^([a-fA-F0-9]{64}|(sha1|sha256|sha512|md5):([a-fA-F0-9]{32}|[a-fA-F0-9]{40}|[a-fA-F0-9]{64}|[a-fA-F0-9]{128}))$",
        "type": "string"
      },
      "jsonPathPattern": {
        "pattern": "^\\$[.\\[].*$",
        "type": "string"
      },
      "hash": {
        "anyOf": [
          {
            "$ref": "#/definitions/hashPattern"
          },
          {
            "items": {
              "$ref": "#/definitions/hashPattern"
            },
            "minItems": 1,
            "type": "array",
            "uniqueItems": true
          }
        ]
      },
      "hashExtraction": {
        "additionalProperties": false,
        "properties": {
          "find": {
            "format": "regex",
            "type": "string",
            "description": "Same as 'regex'"
          },
          "regex": {
            "format": "regex",
            "type": "string"
          },
          "jp": {
            "$ref": "#/definitions/jsonPathPattern",
            "description": "Same as 'jsonpath'"
          },
          "jsonpath": {
            "$ref": "#/definitions/jsonPathPattern"
          },
          "xpath": {
            "type": "string"
          },
          "mode": {
            "enum": [
              "download",
              "extract",
              "json",
              "xpath",
              "rdf",
              "metalink",
              "fosshub",
              "sourceforge",
              "github"
            ]
          },
          "type": {
            "enum": [
              "md5",
              "sha1",
              "sha256",
              "sha512"
            ],
            "description": "Deprecated, hash type is determined automatically"
          },
          "url": {
            "anyOf": [
              {
                "format": "uri",
                "type": "string"
              },
              {
                "pattern": "^(\\$url|\\$baseurl).[\\w\\d]+$",
                "type": "string"
              },
              {
                "pattern": "^.*(\\$url|\\$baseurl).*$",
                "type": "string"
              }
            ]
          }
        },
        "type": "object"
      },
      "hashExtractionOrArrayOfHashExtractions": {
        "anyOf": [
          {
            "$ref": "#/definitions/hashExtraction"
          },
          {
            "items": {
              "$ref": "#/definitions/hashExtraction"
            },
            "minItems": 1,
            "type": "array",
            "uniqueItems": false
          }
        ]
      },
      "architecture": {
        "additionalProperties": false,
        "properties": {
          "bin": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
          },
          "checkver": {
            "$ref": "#/definitions/checkver"
          },
          "env_add_path": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "env_set": {
            "type": "object"
          },
          "extract_dir": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "hash": {
            "$ref": "#/definitions/hash"
          },
          "installer": {
            "$ref": "#/definitions/installer"
          },
          "msi": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Deprecated"
          },
          "post_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "post_uninstall": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "pre_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "pre_uninstall": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "shortcuts": {
            "$ref": "#/definitions/shortcutsArray"
          },
          "uninstaller": {
            "$ref": "#/definitions/uninstaller"
          },
          "url": {
            "$ref": "#/definitions/uriOrArrayOfUris"
          }
        },
        "type": "object"
      },
      "arrayOfArrayOfStrings": {
        "items": {
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "type": "array"
        },
        "minItems": 1,
        "type": "array"
      },
      "shortcutsArray": {
        "items": {
          "items": {
            "type": "string"
          },
          "minItems": 2,
          "maxItems": 4,
          "type": "array"
        },
        "minItems": 1,
        "type": "array"
      },
      "autoupdateArch": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "bin": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
          },
          "env_add_path": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "env_set": {
            "type": "object"
          },
          "extract_dir": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "hash": {
            "$ref": "#/definitions/hashExtractionOrArrayOfHashExtractions"
          },
          "installer": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "file": {
                "type": "string"
              }
            }
          },
          "shortcuts": {
            "$ref": "#/definitions/shortcutsArray"
          },
          "url": {
            "$ref": "#/definitions/autoupdateUriOrArrayOfAutoupdateUris"
          }
        }
      },
      "autoupdate": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "architecture": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "32bit": {
                "$ref": "#/definitions/autoupdateArch"
              },
              "64bit": {
                "$ref": "#/definitions/autoupdateArch"
              },
              "arm64": {
                "$ref": "#/definitions/autoupdateArch"
              }
            }
          },
          "bin": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
          },
          "env_add_path": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "env_set": {
            "type": "object"
          },
          "extract_dir": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "hash": {
            "$ref": "#/definitions/hashExtractionOrArrayOfHashExtractions"
          },
          "installer": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "file": {
                "type": "string"
              }
            }
          },
          "license": {
            "$ref": "#/definitions/license"
          },
          "notes": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "persist": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
          },
          "psmodule": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "name": {
                "type": "string"
              }
            }
          },
          "shortcuts": {
            "$ref": "#/definitions/shortcutsArray"
          },
          "url": {
            "$ref": "#/definitions/autoupdateUriOrArrayOfAutoupdateUris"
          }
        }
      },
      "checkver": {
        "anyOf": [
          {
            "format": "regex",
            "type": "string"
          },
          {
            "additionalProperties": false,
            "properties": {
              "github": {
                "format": "uri",
                "type": "string"
              },
              "re": {
                "format": "regex",
                "type": "string",
                "description": "Same as 'regex'"
              },
              "regex": {
                "format": "regex",
                "type": "string"
              },
              "url": {
                "format": "uri",
                "type": "string"
              },
              "jp": {
                "$ref": "#/definitions/jsonPathPattern",
                "description": "Same as 'jsonpath'"
              },
              "jsonpath": {
                "$ref": "#/definitions/jsonPathPattern"
              },
              "xpath": {
                "type": "string"
              },
              "reverse": {
                "description": "Reverse the order of regex matches",
                "type": "boolean"
              },
              "replace": {
                "description": "Allows rearrange the regexp matches",
                "type": "string"
              },
              "useragent": {
                "type": "string"
              },
              "script": {
                "$ref": "#/definitions/stringOrArrayOfStrings",
                "description": "Custom PowerShell script to retrieve application version using more complex approach."
              },
              "sourceforge": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "additionalProperties": false,
                    "properties": {
                      "project": {
                        "type": "string"
                      },
                      "path": {
                        "type": "string"
                      }
                    },
                    "type": "object"
                  }
                ]
              }
            },
            "type": "object"
          }
        ]
      },
      "installer": {
        "additionalProperties": false,
        "properties": {
          "_comment": {
            "description": "Undocumented: only used in scoop-extras/oraclejdk* and scoop-extras/appengine-go",
            "type": "string"
          },
          "args": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "file": {
            "type": "string"
          },
          "script": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "keep": {
            "type": "boolean"
          }
        },
        "type": "object"
      },
      "stringOrArrayOfStrings": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "items": {
              "type": "string"
            },
            "minItems": 1,
            "type": "array"
          }
        ]
      },
      "stringOrArrayOfStringsOrAnArrayOfArrayOfStrings": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "items": {
              "$ref": "#/definitions/stringOrArrayOfStrings"
            },
            "minItems": 1,
            "type": "array"
          }
        ]
      },
      "uninstaller": {
        "properties": {
          "args": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "file": {
            "type": "string"
          },
          "script": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          }
        },
        "oneOf": [
          {
            "required": [
              "file"
            ]
          },
          {
            "required": [
              "script"
            ]
          }
        ],
        "type": "object"
      },
      "uriOrArrayOfUris": {
        "anyOf": [
          {
            "format": "uri",
            "not": {
              "pattern": "(\\$)"
            },
            "type": "string"
          },
          {
            "items": {
              "format": "uri",
              "not": {
                "pattern": "(\\$)"
              },
              "type": "string"
            },
            "minItems": 1,
            "type": "array",
            "uniqueItems": true
          }
        ]
      },
      "autoupdateUriOrArrayOfAutoupdateUris": {
        "anyOf": [
          {
            "format": "uri",
            "type": "string"
          },
          {
            "items": {
              "format": "uri",
              "type": "string"
            },
            "minItems": 1,
            "type": "array",
            "uniqueItems": true
          }
        ]
      },
      "licenseIdentifiers": {
        "type": "string",
        "description": "License identifier based on SPDX License List https://spdx.org/licenses/",
        "examples": [
          "Apache-2.0",
          "BSD-3-Clause",
          "Freeware",
          "GPL-2.0-only",
          "GPL-2.0-or-later",
          "GPL-3.0-only",
          "GPL-3.0-or-later",
          "ISC",
          "LGPL-2.0-only",
          "LGPL-2.0-or-later",
          "LGPL-2.1-only",
          "LGPL-2.1-or-later",
          "LGPL-3.0-only",
          "LGPL-3.0-or-later",
          "MIT",
          "MS-PL",
          "Proprietary",
          "Public Domain",
          "Shareware",
          "Unlicense"
        ]
      },
      "license": {
        "anyOf": [
          {
            "$ref": "#/definitions/licenseIdentifiers"
          },
          {
            "additionalProperties": false,
            "properties": {
              "url": {
                "format": "uri",
                "type": "string"
              },
              "identifier": {
                "$ref": "#/definitions/licenseIdentifiers"
              }
            },
            "required": [
              "identifier"
            ],
            "type": "object"
          }
        ]
      }
    },
    "properties": {
      "$schema": {
        "type": "string",
        "format": "uri"
      },
      "_comment": {
        "description": "Deprecated. Use ## instead.",
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "##": {
        "description": "A comment.",
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "architecture": {
        "additionalProperties": false,
        "properties": {
          "32bit": {
            "$ref": "#/definitions/architecture"
          },
          "64bit": {
            "$ref": "#/definitions/architecture"
          },
          "arm64": {
            "$ref": "#/definitions/architecture"
          }
        },
        "type": "object"
      },
      "autoupdate": {
        "$ref": "#/definitions/autoupdate"
      },
      "bin": {
        "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
      },
      "persist": {
        "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
      },
      "checkver": {
        "$ref": "#/definitions/checkver"
      },
      "cookie": {
        "description": "Undocumented: Found at https://github.com/se35710/scoop-java/search?l=JSON&q=cookie",
        "type": "object"
      },
      "depends": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "description": {
        "type": "string"
      },
      "env_add_path": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "env_set": {
        "type": "object"
      },
      "extract_dir": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "extract_to": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "hash": {
        "$ref": "#/definitions/hash"
      },
      "homepage": {
        "format": "uri",
        "type": "string"
      },
      "innosetup": {
        "description": "True if the installer InnoSetup based. Found in https://github.com/ScoopInstaller/Main/search?l=JSON&q=innosetup",
        "type": "boolean"
      },
      "installer": {
        "$ref": "#/definitions/installer"
      },
      "license": {
        "$ref": "#/definitions/license"
      },
      "msi": {
        "$ref": "#/definitions/stringOrArrayOfStrings",
        "description": "Deprecated"
      },
      "notes": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "post_install": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "post_uninstall": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "pre_install": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "pre_uninstall": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "psmodule": {
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "shortcuts": {
        "$ref": "#/definitions/shortcutsArray"
      },
      "suggest": {
        "additionalProperties": false,
        "patternProperties": {
          "^(.*)$": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          }
        },
        "type": "object"
      },
      "uninstaller": {
        "$ref": "#/definitions/uninstaller"
      },
      "url": {
        "$ref": "#/definitions/uriOrArrayOfUris"
      },
      "version": {
        "pattern": "^[\\w\\.\\-+_]+$",
        "type": "string"
      }
    },
    "if": {
      "properties": {
        "architecture": {
          "properties": {
            "64bit": {
              "properties": {
                "url": false
              }
            },
            "32bit": {
              "properties": {
                "url": false
              }
            },
            "arm64": {
              "properties": {
                "url": false
              }
            }
          }
        }
      }
    },
    "then": {
      "required": [
        "url"
      ]
    },
    "required": [
      "version",
      "homepage",
      "license"
    ],
    "title": "scoop app manifest schema",
    "type": "object"
  }

=== ArudenKun/scoop-bucket/bucket/vlc-portapps.json
{
    "version": "3.0.16-11",
    "description": "A free and open-source, portable, cross-platform media player and streaming media server.",
    "homepage": "https://www.videolan.org/vlc/",
    "license": {
        "identifier": "GPL-2.0-only",
        "url": "https://www.videolan.org/legal.html"
    },
    "persist": [
        "data",
        "vlc-portable.yml"
    ],
    "architecture": {
        "64bit": {
            "url": "https://github.com/portapps/vlc-portable/releases/download/3.0.16-11/vlc-portable-win64-3.0.16-11.7z#/dl.7z",
            "hash": "8a904be312fe68dd8b2205765564dc1e2b32fc7456a9b6f37b292a1e5ca397c3"
        }
    },
    "shortcuts": [
        [
            "vlc-portable.exe",
            "VLC"
        ]
    ],
    "pre_install": "if(!(Test-Path \"$persist_dir\\vlc-portable.yml\")) { New-Item \"$dir\\vlc-portable.yml\" | Out-Null }",
    "checkver": {
        "url": "https://github.com/portapps/vlc-portable/releases",
        "regex": "\\/releases\\/tag\\/(?:v|V)?([\\d.-]+)"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/portapps/vlc-portable/releases/download/$version/vlc-portable-win64-$version.7z#/dl.7z"
            }
        },
        "hash": {
            "url": "$baseurl/checksums.txt"
        }
    },
    "notes": "Installed from Portapps (https://portapps.io/app/vlc-portable/)"
}

=== ArudenKun/scoop-bucket/bucket/armcord.json
{
    "version": "3.2.6",
    "description": "A custom client designed to enhance your Discord experience while keeping everything lightweight.",
    "homepage": "https://github.com/ArmCord/ArmCord",
    "license": "OSL-3.0",
    "architecture": {
        "64bit": {
            "url": "https://github.com/ArmCord/ArmCord/releases/download/v3.2.6/ArmCord.Setup.3.2.6.exe#/dl.7z",
            "hash": "7dab16efb7de5a692da6e2d0a900cea2d68e3a7828c5f1ad27cd180f24acb82e",
            "pre_install": [
                "Expand-7zipArchive \"$dir\\`$PLUGINSDIR\\app-64.7z\" \"$dir\"",
                "Remove-Item \"$dir\\`$*\", \"$dir\\Uninst*\" -Recurse"
            ]
        }
    },
    "pre_uninstall": "Stop-Process -Name 'ArmCord' -ErrorAction SilentlyContinue",
    "bin": "ArmCord.exe",
    "shortcuts": [
        [
            "ArmCord.exe",
            "ArmCord",
            "--user-data-dir=\"$dir\\data\""
        ]
    ],
    "persist": "data",
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/ArmCord/ArmCord/releases/download/v$version/ArmCord.Setup.$version.exe#/dl.7z"
            }
        }
    },
    "##": [
        "\"hash\": {",
        "    \"url\": \"$baseurl/latest.yml\"",
        "    \"regex\": \"sha512:\\s$base64\"",
        "}"
    ]
}

=== ArudenKun/scoop-bucket/bucket/axel.json
{
    "version": "2.16.1-1",
    "description": "Lightweight download accelerator",
    "homepage": "https://github.com/axel-download-accelerator/axel",
    "license": "GPL-2.0-or-later",
    "architecture": {
        "64bit": {
            "url": "https://downloads.sourceforge.net/project/unix-utils/axel/2.16.1/axel-2.16.1-1-x86_64.zip",
            "hash": "sha1:308ee956e3f886411ae7494037a0b0b8a87360aa",
            "extract_dir": "axel-2.16.1-1-x86_64"
        },
        "32bit": {
            "url": "https://downloads.sourceforge.net/project/unix-utils/axel/2.16.1/axel-2.16.1-1-i686.zip",
            "hash": "sha1:cc139d906d177295f6c08fd9f282994fd0fe50d3",
            "extract_dir": "axel-2.16.1-1-i686"
        }
    },
    "bin": [
        [
            "axel.exe",
            "axel",
            "-k"
        ]
    ],
    "checkver": {
        "url": "https://sourceforge.net/projects/unix-utils/rss?path=/axel",
        "regex": "axel-([\\d.-]+)-x86_64"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://downloads.sourceforge.net/project/unix-utils/axel/$matchHead/axel-$version-x86_64.zip",
                "extract_dir": "axel-$version-x86_64"
            },
            "32bit": {
                "url": "https://downloads.sourceforge.net/project/unix-utils/axel/$matchHead/axel-$version-i686.zip",
                "extract_dir": "axel-$version-i686"
            }
        }
    }
}

=== ArudenKun/scoop-bucket/bucket/z.lua.json
{
    "version": "1.8.23",
    "description": "cd command replacement",
    "homepage": "https://github.com/skywind3000/z.lua",
    "license": "MIT",
    "notes": "Configure accordingly to 'https://github.com/skywind3000/z.lua#install'",
    "depends": "lua",
    "url": "https://github.com/skywind3000/z.lua/archive/1.8.23.zip",
    "hash": "f4328806e6e87fb05cf1266cd8c03f169124b68fa792e46529f565db130368a6",
    "extract_dir": "z.lua-1.8.23",
    "bin": "z.cmd",
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/skywind3000/z.lua/archive/$version.zip",
        "extract_dir": "z.lua-$version"
    }
}

=== ArudenKun/scoop-bucket/bucket/mumuplayer12-np.json
{
    "version": "3.8.18.2845",
    "description": "MuMu Player 12 Large Screen, Unlimited Games Android 12 | Customize keep-alive apps | Multi-Instance",
    "homepage": "https://mumuglobal.com",
    "license": {
        "identifier": "Freeware",
        "url": "https://www.mumuplayer.com/news/update/20190906/30607_831430.html"
    },
    "url": "http://a11.gdl.netease.com/MuMuNG-setup-V3.8.18.2845-overseas-0417125205.exe#/setup.exe",
    "hash": "md5:435c893e9e93441dd0aba3174de3b9d6",
    "installer": {
        "script": [
            "if (!(is_admin)) { \"$app requires admin rights to $cmd\"; break }",
            "Start-Process -Wait \"$dir\\setup.exe\" \"/S /auto_start=false /fchannel=gw-overseas12 /D=C:\\Program Files\\Netease\\MuMuPlayerGlobal-12.0\" -Verb RunAs",
            "Remove-Item \"$Env:USERPROFILE\\Desktop\\MuMu *Player 12.lnk\""
        ]
    },
    "uninstaller": {
        "script": [
            "if (!(is_admin)) { \"$app requires admin rights to $cmd\"; break }",
            "elseif ($cmd -eq \"uninstall\") {",
            "    $uninstaller = (Get-ItemProperty -ErrorAction Ignore \"HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\MuMuPlayerGlobal-12.0\" -Name UninstallString).UninstallString",
            "    if (!$uninstaller) { $uninstaller = (Get-ItemProperty -ErrorAction Ignore \"HKLM:\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\MuMuPlayerGlobal-12.0\" -Name UninstallString).UninstallString }",
            "    if (!$uninstaller) { warn 'Could not find app info in registry' }",
            "    # Remove the quotation on both sides",
            "    $uninstaller = $uninstaller.Substring(1, $uninstaller.Length - 2)",
            "    Start-Process -Wait \"$uninstaller\" \"/S \" -Verb RunAs",
            "}"
        ]
    },
    "checkver": {
        "script": [
            "$url = \"https://api.mumuglobal.com/api/v1/download/nemux?architecture=x86_64&machine=%22%22&usage=1\"",
            "$response = Invoke-RestMethod -Uri $url -Method Post",
            "Write-Output $response.data.mumu.version $response.data.mumu.checksum $response.data.mumu.link"
        ],
        "regex": "([\\d.]+)\\s([A-Z\\d]{32})\\s(.*)"
    },
    "autoupdate": {
        "url": "$match3#/setup.exe",
        "hash": {
            "url": "http://httpbin.org/get?md5=$match2",
            "regex": "md5=.*?$md5"
        }
    }
}

=== ArudenKun/scoop-bucket/bucket/pocketbase.json
{
    "version": "0.40.5",
    "description": "Open Source backend for your next SaaS and Mobile app in 1 file",
    "homepage": "https://pocketbase.io/",
    "license": "MIT",
    "url": "https://github.com/pocketbase/pocketbase/releases/download/v0.40.5/pocketbase_0.40.5_windows_amd64.zip",
    "hash": "d0980d1f3a8097ff4c03a876e8c98f3008a83c0d42cc03b636bc92b2d4788d1c",
    "bin": "pocketbase.exe",
    "persist": "pb_data",
    "checkver": {
        "github": "https://github.com/pocketbase/pocketbase"
    },
    "autoupdate": {
        "url": "https://github.com/pocketbase/pocketbase/releases/download/v$version/pocketbase_$version_windows_amd64.zip",
        "hash": {
            "url": "https://github.com/pocketbase/pocketbase/releases/download/v$version/checksums.txt"
        },
        "extract_dir": "pocketbase_$version_windows_amd64"
    }
}

=== ArudenKun/scoop-bucket/bucket/dorion.json
{
    "version": "6.13.2",
    "description": "Tiny alternative Discord client with a smaller footprint, themes and plugins, multi-profile, and more!",
    "homepage": "https://github.com/SpikeHD/Dorion",
    "license": {
        "identifier": "GPL-3.0",
        "url": "https://github.com/SpikeHD/Dorion/blob/main/LICENSE"
    },
    "architecture": {
        "64bit": {
            "url": "https://github.com/SpikeHD/Dorion/releases/download/v6.13.2/Dorion_6.13.2_win64_portable.zip",
            "hash": "65a8c72a0fb32ec3aa50a73f91451b3b2ea30c801cd6ad0bb14f5e4913e11b8e"
        },
        "arm64": {
            "url": "https://github.com/SpikeHD/Dorion/releases/download/v6.13.2/Dorion_6.13.2_win_arm64_portable.zip",
            "hash": "486228334d629b61f60a247dac01c43014a26b59c0b1aef41165d0ddce6de019"
        }
    },
    "pre_install": [
        "$files = @('config.json', 'detectables.json')",
        "if (-not (Test-Path -Path $persist_dir)) {",
        "    New-Item -Path $persist_dir -ItemType Directory",
        "}",
        "foreach ($file in $files) {",
        "    if (-not (Test-Path -Path (Join-Path $persist_dir $file))) {",
        "        New-Item -Path (Join-Path $persist_dir $file)",
        "    }",
        "}"
    ],
    "post_install": [
        "$sourceFolders = @(\"~\\dorion\", \"$env:APPDATA\\dorion\")",
        "$canMoveFolders = $false",
        "foreach ($sourceFolder in $sourceFolders) {",
        "    If (Test-Path -Path \"$sourceFolder\\*\") {$canMoveFolders = $true; break}",
        "}",
        "If ($canMoveFolders) {",
        "    $confirm = Read-Host -Prompt \"Do you want to move the current data to '$persist_dir'? (Y/N)\"",
        "    If ($confirm.ToUpper() -eq \"Y\") {",
        "        foreach ($sourceFolder in $sourceFolders) {",
        "            If (Test-Path -Path \"$sourceFolder\") {",
        "                If (Test-Path -Path \"$sourceFolder\") {Move-Item -Path \"$sourceFolder\\*\" -Destination \"$persist_dir\" -Force}",
        "                Remove-Item \"$sourceFolder\" -Force -Recurse",
        "            }",
        "        }",
        "    }",
        "}",
        "Remove-Item \"$dir\\*.original\" -Force -Recurse"
    ],
    "shortcuts": [
        [
            "Dorion.exe",
            "Dorion"
        ]
    ],
    "persist": [
        "config.json",
        "detectables.json",
        "plugins",
        "logs",
        "themes",
        "profiles",
        "extensions"
    ],
    "checkver": "github",
    "autoupdate": {
        "extract_dir": "Dorion_$version_win64_portable",
        "architecture": {
            "64bit": {
                "url": "https://github.com/SpikeHD/Dorion/releases/download/v$version/Dorion_$version_win64_portable.zip"
            },
            "arm64": {
                "url": "https://github.com/SpikeHD/Dorion/releases/download/v$version/Dorion_$version_win_arm64_portable.zip"
            }
        }
    }
}
