=== ArudenKun/scoop-bucket/scoop-schema.json
{
    "$id": "http://scoop.sh/draft/schema#",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "definitions": {
      "hashPattern": {
        "pattern": "^([a-fA-F0-9]{64}|(sha1|sha256|sha512|md5):([a-fA-F0-9]{32}|[a-fA-F0-9]{40}|[a-fA-F0-9]{64}|[a-fA-F0-9]{128}))$",
        "type": "string"
      },
      "jsonPathPattern": {
        "pattern": "^\\$[.\\[].*$",
        "type": "string"
      },
      "hash": {
        "anyOf": [
          {
            "$ref": "#/definitions/hashPattern"
          },
          {
            "items": {
              "$ref": "#/definitions/hashPattern"
            },
            "minItems": 1,
            "type": "array",
            "uniqueItems": true
          }
        ]
      },
      "hashExtraction": {
        "additionalProperties": false,
        "properties": {
          "find": {
            "format": "regex",
            "type": "string",
            "description": "Same as 'regex'"
          },
          "regex": {
            "format": "regex",
            "type": "string"
          },
          "jp": {
            "$ref": "#/definitions/jsonPathPattern",
            "description": "Same as 'jsonpath'"
          },
          "jsonpath": {
            "$ref": "#/definitions/jsonPathPattern"
          },
          "xpath": {
            "type": "string"
          },
          "mode": {
            "enum": [
              "download",
              "extract",
              "json",
              "xpath",
              "rdf",
              "metalink",
              "fosshub",
              "sourceforge",
              "github"
            ]
          },
          "type": {
            "enum": [
              "md5",
              "sha1",
              "sha256",
              "sha512"
            ],
            "description": "Deprecated, hash type is determined automatically"
          },
          "url": {
            "anyOf": [
              {
                "format": "uri",
                "type": "string"
              },
              {
                "pattern": "^(\\$url|\\$baseurl).[\\w\\d]+$",
                "type": "string"
              },
              {
                "pattern": "^.*(\\$url|\\$baseurl).*$",
                "type": "string"
              }
            ]
          }
        },
        "type": "object"
      },
      "hashExtractionOrArrayOfHashExtractions": {
        "anyOf": [
          {
            "$ref": "#/definitions/hashExtraction"
          },
          {
            "items": {
              "$ref": "#/definitions/hashExtraction"
            },
            "minItems": 1,
            "type": "array",
            "uniqueItems": false
          }
        ]
      },
      "architecture": {
        "additionalProperties": false,
        "properties": {
          "bin": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
          },
          "checkver": {
            "$ref": "#/definitions/checkver"
          },
          "env_add_path": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "env_set": {
            "type": "object"
          },
          "extract_dir": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "hash": {
            "$ref": "#/definitions/hash"
          },
          "installer": {
            "$ref": "#/definitions/installer"
          },
          "msi": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Deprecated"
          },
          "post_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "post_uninstall": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "pre_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "pre_uninstall": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "shortcuts": {
            "$ref": "#/definitions/shortcutsArray"
          },
          "uninstaller": {
            "$ref": "#/definitions/uninstaller"
          },
          "url": {
            "$ref": "#/definitions/uriOrArrayOfUris"
          }
        },
        "type": "object"
      },
      "arrayOfArrayOfStrings": {
        "items": {
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "type": "array"
        },
        "minItems": 1,
        "type": "array"
      },
      "shortcutsArray": {
        "items": {
          "items": {
            "type": "string"
          },
          "minItems": 2,
          "maxItems": 4,
          "type": "array"
        },
        "minItems": 1,
        "type": "array"
      },
      "autoupdateArch": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "bin": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
          },
          "env_add_path": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "env_set": {
            "type": "object"
          },
          "extract_dir": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "hash": {
            "$ref": "#/definitions/hashExtractionOrArrayOfHashExtractions"
          },
          "installer": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "file": {
                "type": "string"
              }
            }
          },
          "shortcuts": {
            "$ref": "#/definitions/shortcutsArray"
          },
          "url": {
            "$ref": "#/definitions/autoupdateUriOrArrayOfAutoupdateUris"
          }
        }
      },
      "autoupdate": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "architecture": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "32bit": {
                "$ref": "#/definitions/autoupdateArch"
              },
              "64bit": {
                "$ref": "#/definitions/autoupdateArch"
              },
              "arm64": {
                "$ref": "#/definitions/autoupdateArch"
              }
            }
          },
          "bin": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
          },
          "env_add_path": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "env_set": {
            "type": "object"
          },
          "extract_dir": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "hash": {
            "$ref": "#/definitions/hashExtractionOrArrayOfHashExtractions"
          },
          "installer": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "file": {
                "type": "string"
              }
            }
          },
          "license": {
            "$ref": "#/definitions/license"
          },
          "notes": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "persist": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
          },
          "psmodule": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "name": {
                "type": "string"
              }
            }
          },
          "shortcuts": {
            "$ref": "#/definitions/shortcutsArray"
          },
          "url": {
            "$ref": "#/definitions/autoupdateUriOrArrayOfAutoupdateUris"
          }
        }
      },
      "checkver": {
        "anyOf": [
          {
            "format": "regex",
            "type": "string"
          },
          {
            "additionalProperties": false,
            "properties": {
              "github": {
                "format": "uri",
                "type": "string"
              },
              "re": {
                "format": "regex",
                "type": "string",
                "description": "Same as 'regex'"
              },
              "regex": {
                "format": "regex",
                "type": "string"
              },
              "url": {
                "format": "uri",
                "type": "string"
              },
              "jp": {
                "$ref": "#/definitions/jsonPathPattern",
                "description": "Same as 'jsonpath'"
              },
              "jsonpath": {
                "$ref": "#/definitions/jsonPathPattern"
              },
              "xpath": {
                "type": "string"
              },
              "reverse": {
                "description": "Reverse the order of regex matches",
                "type": "boolean"
              },
              "replace": {
                "description": "Allows rearrange the regexp matches",
                "type": "string"
              },
              "useragent": {
                "type": "string"
              },
              "script": {
                "$ref": "#/definitions/stringOrArrayOfStrings",
                "description": "Custom PowerShell script to retrieve application version using more complex approach."
              },
              "sourceforge": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "additionalProperties": false,
                    "properties": {
                      "project": {
                        "type": "string"
                      },
                      "path": {
                        "type": "string"
                      }
                    },
                    "type": "object"
                  }
                ]
              }
            },
            "type": "object"
          }
        ]
      },
      "installer": {
        "additionalProperties": false,
        "properties": {
          "_comment": {
            "description": "Undocumented: only used in scoop-extras/oraclejdk* and scoop-extras/appengine-go",
            "type": "string"
          },
          "args": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "file": {
            "type": "string"
          },
          "script": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "keep": {
            "type": "boolean"
          }
        },
        "type": "object"
      },
      "stringOrArrayOfStrings": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "items": {
              "type": "string"
            },
            "minItems": 1,
            "type": "array"
          }
        ]
      },
      "stringOrArrayOfStringsOrAnArrayOfArrayOfStrings": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "items": {
              "$ref": "#/definitions/stringOrArrayOfStrings"
            },
            "minItems": 1,
            "type": "array"
          }
        ]
      },
      "uninstaller": {
        "properties": {
          "args": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          },
          "file": {
            "type": "string"
          },
          "script": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          }
        },
        "oneOf": [
          {
            "required": [
              "file"
            ]
          },
          {
            "required": [
              "script"
            ]
          }
        ],
        "type": "object"
      },
      "uriOrArrayOfUris": {
        "anyOf": [
          {
            "format": "uri",
            "not": {
              "pattern": "(\\$)"
            },
            "type": "string"
          },
          {
            "items": {
              "format": "uri",
              "not": {
                "pattern": "(\\$)"
              },
              "type": "string"
            },
            "minItems": 1,
            "type": "array",
            "uniqueItems": true
          }
        ]
      },
      "autoupdateUriOrArrayOfAutoupdateUris": {
        "anyOf": [
          {
            "format": "uri",
            "type": "string"
          },
          {
            "items": {
              "format": "uri",
              "type": "string"
            },
            "minItems": 1,
            "type": "array",
            "uniqueItems": true
          }
        ]
      },
      "licenseIdentifiers": {
        "type": "string",
        "description": "License identifier based on SPDX License List https://spdx.org/licenses/",
        "examples": [
          "Apache-2.0",
          "BSD-3-Clause",
          "Freeware",
          "GPL-2.0-only",
          "GPL-2.0-or-later",
          "GPL-3.0-only",
          "GPL-3.0-or-later",
          "ISC",
          "LGPL-2.0-only",
          "LGPL-2.0-or-later",
          "LGPL-2.1-only",
          "LGPL-2.1-or-later",
          "LGPL-3.0-only",
          "LGPL-3.0-or-later",
          "MIT",
          "MS-PL",
          "Proprietary",
          "Public Domain",
          "Shareware",
          "Unlicense"
        ]
      },
      "license": {
        "anyOf": [
          {
            "$ref": "#/definitions/licenseIdentifiers"
          },
          {
            "additionalProperties": false,
            "properties": {
              "url": {
                "format": "uri",
                "type": "string"
              },
              "identifier": {
                "$ref": "#/definitions/licenseIdentifiers"
              }
            },
            "required": [
              "identifier"
            ],
            "type": "object"
          }
        ]
      }
    },
    "properties": {
      "$schema": {
        "type": "string",
        "format": "uri"
      },
      "_comment": {
        "description": "Deprecated. Use ## instead.",
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "##": {
        "description": "A comment.",
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "architecture": {
        "additionalProperties": false,
        "properties": {
          "32bit": {
            "$ref": "#/definitions/architecture"
          },
          "64bit": {
            "$ref": "#/definitions/architecture"
          },
          "arm64": {
            "$ref": "#/definitions/architecture"
          }
        },
        "type": "object"
      },
      "autoupdate": {
        "$ref": "#/definitions/autoupdate"
      },
      "bin": {
        "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
      },
      "persist": {
        "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
      },
      "checkver": {
        "$ref": "#/definitions/checkver"
      },
      "cookie": {
        "description": "Undocumented: Found at https://github.com/se35710/scoop-java/search?l=JSON&q=cookie",
        "type": "object"
      },
      "depends": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "description": {
        "type": "string"
      },
      "env_add_path": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "env_set": {
        "type": "object"
      },
      "extract_dir": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "extract_to": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "hash": {
        "$ref": "#/definitions/hash"
      },
      "homepage": {
        "format": "uri",
        "type": "string"
      },
      "innosetup": {
        "description": "True if the installer InnoSetup based. Found in https://github.com/ScoopInstaller/Main/search?l=JSON&q=innosetup",
        "type": "boolean"
      },
      "installer": {
        "$ref": "#/definitions/installer"
      },
      "license": {
        "$ref": "#/definitions/license"
      },
      "msi": {
        "$ref": "#/definitions/stringOrArrayOfStrings",
        "description": "Deprecated"
      },
      "notes": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "post_install": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "post_uninstall": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "pre_install": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "pre_uninstall": {
        "$ref": "#/definitions/stringOrArrayOfStrings"
      },
      "psmodule": {
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "shortcuts": {
        "$ref": "#/definitions/shortcutsArray"
      },
      "suggest": {
        "additionalProperties": false,
        "patternProperties": {
          "^(.*)$": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
          }
        },
        "type": "object"
      },
      "uninstaller": {
        "$ref": "#/definitions/uninstaller"
      },
      "url": {
        "$ref": "#/definitions/uriOrArrayOfUris"
      },
      "version": {
        "pattern": "^[\\w\\.\\-+_]+$",
        "type": "string"
      }
    },
    "if": {
      "properties": {
        "architecture": {
          "properties": {
            "64bit": {
              "properties": {
                "url": false
              }
            },
            "32bit": {
              "properties": {
                "url": false
              }
            },
            "arm64": {
              "properties": {
                "url": false
              }
            }
          }
        }
      }
    },
    "then": {
      "required": [
        "url"
      ]
    },
    "required": [
      "version",
      "homepage",
      "license"
    ],
    "title": "scoop app manifest schema",
    "type": "object"
  }

=== ArudenKun/scoop-bucket/deprecated/cheat-engine.json
{
    "version": "7.4",
    "description": "Tool for modifying/debugging single player games and applications.",
    "homepage": "https://cheatengine.org/index.php",
    "license": {
        "identifier": "Freeware",
        "url": "https://github.com/cheat-engine/cheat-engine/issues/60#issuecomment-467317576"
    },
    "url": "https://kemono.party/data/4a/82/4a82b61b748175780a28c17dbbd8efaef59b1ed2d95cf91df08b8c8572368b9c.bin?f=CheatEngine74P.exe",
    "hash": "4A82B61B748175780A28C17DBBD8EFAEF59B1ED2D95CF91DF08B8C8572368B9C",
    "innosetup": true,
    "architecture": {
        "64bit": {
            "shortcuts": [
                [
                    "Cheat Engine.exe",
                    "Cheat Engine"
                ],
                [
                    "windowsrepair.exe",
                    "Cheat Engine Windows Repair"
                ],
                [
                    "Tutorial-x86_64.exe",
                    "Cheat Engine Tutorial"
                ]
            ]
        },
        "32bit": {
            "shortcuts": [
                [
                    "Cheat Engine.exe",
                    "Cheat Engine"
                ],
                [
                    "windowsrepair.exe",
                    "Cheat Engine Windows Repair"
                ],
                [
                    "Tutorial-i386.exe",
                    "Cheat Engine Tutorial"
                ]
            ]
        }
    }
}

=== ArudenKun/scoop-bucket/bucket/openvpn-win10-portapps.json
{
    "version": "2.4.7-I607-Win10-5",
    "description": "A free and open-source software application that implements virtual private network (VPN) techniques.",
    "homepage": "https://openvpn.net",
    "license": {
        "identifier": "GPL-2.0-only",
        "url": "https://openvpn.net/terms/"
    },
    "persist": [
        "data",
        "openvpn-portable.yml"
    ],
    "architecture": {
        "64bit": {
            "url": "https://github.com/portapps/openvpn-portable/releases/download/2.4.7-I607-Win10-5/openvpn-portable-win64-2.4.7-I607-Win10-5.7z#/dl.7z",
            "hash": "5fa00c5fec5b2d0097e66987c0133788a1e603c46a6f02b326997e120b28c4d3"
        },
        "32bit": {
            "url": "https://github.com/portapps/openvpn-portable/releases/download/2.4.7-I607-Win10-5/openvpn-portable-win32-2.4.7-I607-Win10-5.7z#/dl.7z",
            "hash": "4fff6bbe168b4e2581f960a3eeb869d6ebb04a5be7500f3fa15dd41f1cf8bbdb"
        }
    },
    "shortcuts": [
        [
            "openvpn-portable.exe",
            "OpenVPN"
        ]
    ],
    "pre_install": "if(!(Test-Path \"$persist_dir\\openvpn-portable.yml\")) { New-Item \"$dir\\openvpn-portable.yml\" | Out-Null }",
    "checkver": {
        "url": "https://github.com/portapps/openvpn-portable/releases",
        "regex": "\\/releases\\/tag\\/(?:v|V)?([I\\d.-]+Win10-[\\d]+)"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/portapps/openvpn-portable/releases/download/$version/openvpn-portable-win64-$version.7z#/dl.7z"
            },
            "32bit": {
                "url": "https://github.com/portapps/openvpn-portable/releases/download/$version/openvpn-portable-win32-$version.7z#/dl.7z"
            }
        },
        "hash": {
            "url": "$baseurl/checksums.txt"
        }
    },
    "notes": "Installed from Portapps (https://portapps.io/app/openvpn-portable/)"
}

=== ArudenKun/scoop-bucket/bucket/messenger.json
{
    "version": "1530.18.110.0",
    "description": "A simple app that lets you text, video chat, and stay close with people you care about.",
    "homepage": "https://www.messenger.com/desktop",
    "license": "Proprietary",
    "url": "https://aruden-scoop-bucket-api.deno.dev/appxmessenger?dl#/FACEBOOK.317180B0BB486_1530.18.110.0_x64__8xx8rvfyw5nnt.appx.7z",
    "hash": "sha1:d7e2b828eafc0d24269efd713e7b27a677633097",
    "shortcuts": [
        [
            "Messenger.exe",
            "Messenger"
        ]
    ],
    "post_install": "Remove-Item $dir/app",
    "checkver": {
        "url": "https://aruden-scoop-bucket-api.deno.dev/appxmessenger",
        "jsonpath": "$.version"
    },
    "autoupdate": {
        "url": "https://aruden-scoop-bucket-api.deno.dev/appxmessenger?dl#/FACEBOOK.317180B0BB486_$version_x64__8xx8rvfyw5nnt.appx.7z",
        "hash": {
            "url": "https://aruden-scoop-bucket-api.deno.dev/appxmessenger",
            "jsonpath": "$.sha1"
        }
    }
}

=== ArudenKun/scoop-bucket/bucket/compactgui-alpha.json
{
    "version": "3.0.0-alpha.7",
    "description": "CompactGUI is a standalone user interface that makes the Windows 10 compact.exe function easier to use.",
    "homepage": "https://github.com/ImminentFate/CompactGUI",
    "license": "GPL-3.0-only",
    "url": "https://github.com/IridiumIO/CompactGUI/releases/download/v3.0.0-alpha.6/CompactGUI.exe",
    "hash": "9e0138f3330f524851c0eae6dc24499bbacd3eaee9fdd1418dac1c714e8bfcb7",
    "bin": "CompactGUI.exe",
    "shortcuts": [
        [
            "CompactGUI.exe",
            "CompactGUI Alpha"
        ]
    ],
    "checkver": {
        "url": "https://github.com/IridiumIO/CompactGUI/tags",
        "regex": "/archive/refs/tags/v(?<ver>\\d(\\.\\d)+)-alpha\\.(?<alpha>\\d)\\.zip",
        "replace": "${ver}-alpha.${alpha}"
    },
    "autoupdate": {
        "url": "https://github.com/IridiumIO/CompactGUI/releases/download/v3.0.0-alpha.6/CompactGUI.exe",
        "hash": {
            "url": "https://github.com/IridiumIO/CompactGUI/releases/tag/v$version/",
            "regex": "SHA-256</span>:\\s+<span\\sclass=\"pl-s\">$sha256"
        }
    }
}

=== ArudenKun/scoop-bucket/bucket/pipx.json
{
    "version": "1.17.8",
    "description": "Install and run Python applications in isolated environments",
    "homepage": "https://pipx.pypa.io/",
    "license": "MIT",
    "suggest": {
        "Python": "python"
    },
    "pre_install": "Set-Content -Value '@python \"%~dp0pipx.pyz\" %*' -Path \"$dir\\pipx.bat\"",
    "url": "https://github.com/pypa/pipx/releases/download/1.17.8/pipx.pyz",
    "hash": "a5827798e78767c7f83c7261400e3521a68c18cae9f6635ad7fe739290cb3e87",
    "bin": "pipx.bat",
    "env_add_path": "data\\bin",
    "env_set": {
        "PIPX_HOME": "$dir\\data",
        "PIPX_BIN_DIR": "$dir\\data\\bin",
        "PIPX_MAN_DIR": "$dir\\data\\share\\man"
    },
    "persist": "data",
    "checkver": {
        "github": "https://github.com/pypa/pipx"
    },
    "autoupdate": {
        "url": "https://github.com/pypa/pipx/releases/download/$version/pipx.pyz"
    }
}

=== ArudenKun/scoop-bucket/deprecated/yuukips-dockergs.json
{
    "version": "436115635",
    "description": "DockerGS is a container that run Grasscutter (anime game) with just a single command.",
    "homepage": "https://github.com/akbaryahya/DockerGS",
    "license": "AGPL-3.0",
    "depends": [
        "temurin17-jdk",
        "yuukips-resource"
    ],
    "url": "https://nightly.link/akbaryahya/DockerGS/actions/artifacts/436115635.zip",
    "hash": "6aa8bdff0ae7c4f7c6b7ad2aa3e500d059cad66479814f96a5707dec48bb5aba",
    "pre_install": [
        "if (!(Test-Path \"$persist_dir\\config.json\"))",
        "{",
        "    Copy-Item \"$bucketsdir\\custom\\scripts\\yuukips\\config.json\" \"$dir\"",
        "}",
        "Set-Content \"$dir\\dockergs.bat\" 'java -jar \"%~dp0grasscutter.jar\" %1' -Encoding Ascii"
    ],
    "bin": "dockergs.bat",
    "persist": [
        "cache",
        "data",
        "logs",
        "plugins",
        "config.json"
    ],
    "post_install": [
        "$config = Get-Content \"$dir\\config.json\" | ConvertFrom-Json",
        "$config.folderStructure.resources = \"$(appdir yuukips-resource)\\current\\resources.zip\"",
        "$config | ConvertTo-Json -Depth 10 | Set-Content \"$dir\\config.json\""
    ],
    "checkver": {
        "url": "https://nightly.link/akbaryahya/DockerGS/workflows/DockerGS_GC_Alpine_3.2/main/DockerGS-GC",
        "regex": "(\\d+).zip"
    },
    "autoupdate": {
        "url": "https://nightly.link/akbaryahya/DockerGS/actions/artifacts/$version.zip"
    }
}

=== ArudenKun/scoop-bucket/deprecated/rare.json
{
    "version": "1.11.3.332",
    "description": "A frontend for legendary, the open source Epic Games Launcher alternative.",
    "homepage": "https://github.com/Dummerle/Rare",
    "license": "GPL-3.0-only",
    "architecture": {
        "64bit": {
            "url": "https://github.com/Dummerle/Rare/releases/download/1.11.3.332/Rare-1.11.3.332.msi",
            "hash": "c5b1727b9a01818bb22704bf993fe744f2e8a9025e39406e8febd340f118e28b"
        }
    },
    "bin": "Rare.exe",
    "shortcuts": [
        [
            "Rare.exe",
            "Rare"
        ]
    ],
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/Dummerle/Rare/releases/download/$version/Rare-$version.msi"
            }
        }
    }
}

=== ArudenKun/scoop-bucket/bucket/suwayomi-server-preview.json
{
    "version": "2.4.2379",
    "description": "A manga reader compatible with Tachiyomi extensions and backups",
    "homepage": "https://github.com/Suwayomi/Suwayomi-Server-preview",
    "license": {
        "identifier": "MPL-2.0",
        "url": "https://github.com/Suwayomi/Suwayomi-Server/blob/master/LICENSE"
    },
    "architecture": {
        "64bit": {
            "url": [
                "https://github.com/Suwayomi/Suwayomi-Server-preview/releases/download/v2.4.2379/Suwayomi-Server-v2.4.2379-windows-x64.zip",
                "https://raw.githubusercontent.com/Suwayomi/Suwayomi-Server/master/server/src/main/resources/icon/faviconlogo.ico",
                "https://github.com/ScoopInstaller/Extras/raw/master/scripts/suwayomi-server/suwayomi.ps1#/suwayomi-server-launcher.ps1"
            ],
            "hash": [
                "c5dc07727815810f6f577dbf1f7f3d3382e23c780f5c2180cdffdd88fabe92ae",
                "3e5b32450bc8659f41b5da5b85a246d8e500ea5b93c917abb8032e6f80068550",
                "f7d32050ace8bcb05005a65da1dae174e3eeca86a370e769639f5c0d03e61629"
            ],
            "extract_dir": "Suwayomi-Server-v2.4.2379-windows-x64"
        }
    },
    "pre_install": "Set-Content \"$dir\\suwayomi-server.ps1\" -Value \"& $dir\\jre\\bin\\java `\"-Dsuwayomi.tachidesk.config.server.rootDir=$dir\\data`\" -jar $dir\\bin\\Suwayomi-Server.jar\" -Encoding Ascii",
    "post_install": [
        "if (Test-Path $env:LOCALAPPDATA\\Tachidesk) {",
        "    Copy-Item -Path $env:LOCALAPPDATA\\Tachidesk\\* -Destination \"$persist_dir\\data\" -Force -Recurse",
        "    Remove-Item $env:LOCALAPPDATA\\Tachidesk -Force -Recurse",
        "}"
    ],
    "bin": [
        [
            "suwayomi-server-launcher.ps1",
            "suwayomi-server-preview-launcher"
        ],
        [
            "suwayomi-server.ps1",
            "suwayomi-server-preview"
        ]
    ],
    "shortcuts": [
        [
            "Suwayomi Launcher.bat",
            "Suwayomi Server Preview Launcher",
            "",
            "faviconlogo.ico"
        ],
        [
            "suwayomi-server.ps1",
            "Suwayomi Server Preview",
            "",
            "faviconlogo.ico"
        ]
    ],
    "persist": "data",
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/Suwayomi/Suwayomi-Server-preview/releases/download/v$version/Suwayomi-Server-v$version-windows-x64.zip",
                "extract_dir": "Suwayomi-Server-v$version-windows-x64"
            }
        }
    }
}
